### ISSUE TITLE
训不出27帧的模型

### ISSUE THREAD

**Issue by 1049-xxw** [zhenhuat/STCFormer#10]
请教一下为什么为根据指示训练27帧的模型，没有在第6轮训出44.06的p1指标？

**Comment by zhenhuat** [comment]
> 请教一下为什么为根据指示训练27帧的模型，没有在第6轮训出44.06的p1指标？

请问您训练出来的结果是多少呢？

**Comment by 1049-xxw** [comment]
46\47的样子，请问这个模型的训练是跟batchsize有关系吗？我每次都是用gpu的最大内存去跑的模型，请您解惑。

**Comment by zhenhuat** [comment]
> 46\47的样子，请问这个模型的训练是跟batchsize有关系吗？我每次都是用gpu的最大内存去跑的模型，请您解惑。

哈喽，这个偏差有点大。你可以参考这个回答调整超参，https://github.com/zhenhuat/STCFormer/issues/2#issuecomment-1675513578

**Comment by 1049-xxw** [comment]
根据里面的描述，get_batch（）的代码是正确的，我现在试着修改为x_s = att_s @ v_s + sep2_s + 0.001 * self.drop(sep_s)试试。

**Comment by 1049-xxw** [comment]
我重新训练了一波，结果如下，请问这个误差是否在合理范围

![图片](https://github.com/zhenhuat/STCFormer/assets/57626938/b3d3cc89-343a-4b07-980e-0c4a65d9ab24)

**Comment by 1049-xxw** [comment]
我重新训练了一波，结果如下，这个误差是否在合理范围

![图片](https://github.com/zhenhuat/STCFormer/assets/57626938/b3d3cc89-343a-4b07-980e-0c4a65d9ab24)

**Comment by zhenhuat** [comment]
> 我重新训练了一波，结果如下，请问这个误差是否在合理范围
> 
> ![图片](https://private-user-images.githubusercontent.com/57626938/322740669-b3d3cc89-343a-4b07-980e-0c4a65d9ab24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjAyMjksIm5iZiI6MTcxMzI1OTkyOSwicGF0aCI6Ii81NzYyNjkzOC8zMjI3NDA2NjktYjNkM2NjODktMzQzYS00YjA3LTk4MGUtMGM0YTY1ZDlhYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjViNzMzMGM5M2U3MGMzZDIzZDIwN2U0MzhjNDNhZDZmYjViZDJlZDQ4NWNiOGFkZjk4YzY5ZmQ5OTU0MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ceUyONOmmIpIQnEi7bGVDXZ8TdtTxypz8D_dt8333VY)

比之前正常了，44.1上下0.5mm。如果有时间可以再调下超参试试，主要是s 和 batch。

**Comment by 1049-xxw** [comment]
您好，如果有可能，能不能教我一下具体该怎么调，因为我是刚入门这个方向，而且这个东西训一次也要一天左右，万分感谢。

**Comment by zhenhuat** [comment]
> 您好，如果有可能，能不能教我一下具体该怎么调，因为我是刚入门这个方向，而且这个东西训一次也要一天左右，万分感谢。

 python run_stc.py -f 27 -b 128 --train 1 --layers 6 -s 3   运行脚本里的这些就试主要的超参，f是帧数；b是batch_size；s是采样系数。要是27帧你的机器都得训练一天的话，可能做这个任务有点难度，因为243帧需要的算力是27帧的30倍。

**Comment by 1049-xxw** [comment]
感谢指导和提醒！目前用的是3090，训练27帧，只是b设置为128， s为3的话训练和测试一轮，将近一个小时四十分钟左右。请问单张4090训243帧是否够用?

**Comment by zhenhuat** [comment]
> 感谢指导和提醒！目前用的是3090，训练27帧，只是b设置为128， s为3的话训练和测试一轮，将近一个小时四十分钟左右。请问单张4090训243帧是否够用?

可以将s设置为9看看结果。另外，4090确实能让训练速度加快，但是3090和4090的问题主要是显存（24G）不够，我之前用A100(40G)才能跑出243帧的最佳性能。

**Comment by 1049-xxw** [comment]
![屏幕截图 2024-04-18 091730](https://github.com/zhenhuat/STCFormer/assets/57626938/45cf03d3-c09a-4192-a2dd-74e01968b26b)
这是修改b和s后的结果，还是在误差范围外

**Comment by zhenhuat** [comment]
> ![屏幕截图 2024-04-18 091730](https://private-user-images.githubusercontent.com/57626938/323432804-45cf03d3-c09a-4192-a2dd-74e01968b26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjYwMjUsIm5iZiI6MTcxMzQyNTcyNSwicGF0aCI6Ii81NzYyNjkzOC8zMjM0MzI4MDQtNDVjZjAzZDMtYzA5YS00MTkyLWEyZGQtNzRlMDE5NjhiMjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NDE4NGYwMWEwNGRmM2I2OWUzY2FjNzE4NjE4MjVjYTYyOTI0ZTc3Y2E3MTJiYzAzMzkxMGEwNTA5YTcwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xpAtbVRxCjgj_JLRDH4wKvCWgJ1-iANFUjmUnnUMtQQ) 这是修改b和s后的结果，还是在误差范围外

44.6差不多吧，你可以再试试python run_stc.py -f 27 -b 128 --train 1 --layers 6 -s 3。 epoch的数目也不是一定6个，这是有随机性的，跟机器和初始化都有关。

**Comment by 1049-xxw** [comment]
哥，能不能在你有空的时候私下闲聊指导我一下？感觉毕不了业了
