### ISSUE TITLE
关于加权平均

### ISSUE THREAD

**Issue by jokerxxw** [zhenhuat/STCFormer#15]
请问作者您之前训练的81帧42.7和27帧的44.1是如何求加权平均的？

**Comment by zhenhuat** [comment]
> 请问作者您之前训练的81帧42.7和27帧的44.1是如何求加权平均的？

你好，加权平均相当于模型的集成emsamble，stcformer在81帧和243帧时使用了这个策略。对于81帧的模型具体方法是：
（1）用27帧的模型和81帧的模型，分别得到测试样本的估计结果（坐标）pose1和pose2；
（2）把上面两组结果相加取均值，得到新的估计结果pose3，作为81帧模型的最终估计姿态；
（3）用pose3去计算误差。
243帧可以和81帧集成，也可以和81,27都集成。

**Comment by jokerxxw** [comment]
请问有具体的代码吗？不胜感激！

**Comment by jokerxxw** [comment]
还有一个问题，关于3dhp数据集，请问您是重新在这个数据集上训练的模型测试出来的结果，还是用human3.6的训练模型？

**Comment by zhenhuat** [comment]
> 还有一个问题，关于3dhp数据集，请问您是重新在这个数据集上训练的模型测试出来的结果，还是用human3.6的训练模型？

（1）代码我找不到了，这个蛮容易实现的，你先把各个模型的估计结果保存到本地就好了。
（2）3dhp的结果是重新训练的。

**Comment by jokerxxw** [comment]
好的，谢谢啦
