### ISSUE TITLE
关于算力要求

### ISSUE THREAD

**Issue by VMC-Lab-Chen** [zhenhuat/STCFormer#16]
作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？

**Comment by zhenhuat** [comment]
> 作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？

同学你好，这个算力瓶颈主要是内存大小，4090有24G还是可以的。刚入门的话，也可以follow [D3DP](https://github.com/paTRICK-swk/D3DP)或者24年的新工作，尝试去把代码run起来。

**Comment by VMC-Lab-Chen** [comment]
> > 作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？
> 
> 同学你好，这个算力瓶颈主要是内存大小，4090有24G还是可以的。刚入门的话，也可以follow [D3DP](https://github.com/paTRICK-swk/D3DP)或者24年的新工作，尝试去把代码run起来。

再请教一下大佬，如果用一张4090的显卡复现您243帧的工作，做一次完整的训练，大概需要训练多长时间？

**Comment by zhenhuat** [comment]
> > > 作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？
> > 
> > 
> > 同学你好，这个算力瓶颈主要是内存大小，4090有24G还是可以的。刚入门的话，也可以follow [D3DP](https://github.com/paTRICK-swk/D3DP)或者24年的新工作，尝试去把代码run起来。
> 
> 再请教一下大佬，如果用一张4090的显卡复现您243帧的工作，做一次完整的训练，大概需要训练多长时间？

4090可以训练的。`python run_stc.py -f 243-b 128 --train 1 --layers 6 -tds 2 -s 3 `，具体时间我不记得了，你可以尝试一下

**Comment by VMC-Lab-Chen** [comment]
> > > > 作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？
> > > 
> > > 
> > > 同学你好，这个算力瓶颈主要是内存大小，4090有24G还是可以的。刚入门的话，也可以follow [D3DP](https://github.com/paTRICK-swk/D3DP)或者24年的新工作，尝试去把代码run起来。
> > 
> > 
> > 再请教一下大佬，如果用一张4090的显卡复现您243帧的工作，做一次完整的训练，大概需要训练多长时间？
> 
> 4090可以训练的。`python run_stc.py -f 243-b 128 --train 1 --layers 6 -tds 2 -s 3 `，具体时间我不记得了，你可以尝试一下

好的，感谢感谢！

**Comment by wanghaoyang66** [comment]
> > > > > 作者您好，我是刚入门这个方向的新人，我想请问一下如果要在这个方向取得一定成果，1张4090显卡可以满足算力要求吗？
> > > > 
> > > > 
> > > > 同学你好，这个算力瓶颈主要是内存大小，4090有24G还是可以的。刚入门的话，也可以follow [D3DP](https://github.com/paTRICK-swk/D3DP)或者24年的新工作，尝试去把代码run起来。
> > > 
> > > 
> > > 再请教一下大佬，如果用一张4090的显卡复现您243帧的工作，做一次完整的训练，大概需要训练多长时间？
> > 
> > 
> > 4090可以训练的。`python run_stc.py -f 243-b 128 --train 1 --layers 6 -tds 2 -s 3 `，具体时间我不记得了，你可以尝试一下
> 
> 好的，感谢感谢！

你好，我想问一下，您使用4090复现出来243帧了吗？
