### ISSUE TITLE
About the epochs

### ISSUE THREAD

**Issue by sk-zhang** [zhenhuat/STCFormer#6]
Could I ask if the general training is to run the set 60 epochs? Or is it ok to stop at the front.

**Comment by zhenhuat** [comment]
> Could I ask if the general training is to run the set 60 epochs? Or is it ok to stop at the front.

Hi, it will converge within 20 epochs on Human3.6M and more on 3DHP.

**Comment by sk-zhang** [comment]
Okay, thanks a lot, I'll close the issue.
